spring.application.name=springboot

spring.datasource.url=jdbc:mysql://localhost:3306/<Your-Database-Name>

spring.datasource.username=<Your-Database-username>
spring.datasource.password=<Your-Database-Password>
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.google.client-id=<Your-Client-Id>
spring.security.oauth2.client.registration.google.client-secret=<Your-Client-Secret>
security.oauth2.client.accessTokenUri= https://www.googleapis.com/oauth2/v3/token
security.oauth2.client.userAuthorizationUri= https://account.google.com/o/oauth2/auth
security.oauth2.client.tokenName= oauth_token
security.oauth2.client.authenticationScheme=query
security.oauth2.client.clientAuthenticationScheme= form
security.oauth2.client.scope=profile email 